### ISSUE TITLE
First message lost

### ISSUE THREAD

**Issue by adminSxs** [snapview/tokio-tungstenite#175]
```toml
tokio={version="1.5",features=["full"]}
tokio-tungstenite="*"
```

![image](https://user-images.githubusercontent.com/15902505/121638889-4bd85d80-cabe-11eb-83a4-e140466c5cd7.png)
