### ISSUE TITLE
Rustls: no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point

### ISSUE THREAD

**Issue by maxpowel** [snapview/tokio-tungstenite#339]
Hello

When using rutls on versions > 0.22.0 this error is raised:
```
[2024-07-05][12:21:59][tokio_tungstenite::tls::encryption::rustls][DEBUG] Added 129/129 native root certificates (ignored 0)
thread 'tokio-runtime-worker' panicked at /home/maxpowel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustls-0.23.10/src/crypto/mod.rs:259:14:
no process-level CryptoProvider available -- call CryptoProvider::install_default() before this point

```
I investigated a bit about CryptoProvider::install_default() and it looks something related with latest changes rustls made in crypto part.

This line in my Cargo.toml works fine:
```
tokio-tungstenite = { version = "0.22.0", features = ["rustls-tls-native-roots"] }
```
but this raises the error
```
tokio-tungstenite = { version = "0.23.1", features = ["rustls-tls-native-roots"] }
```

The error appears as soon as you  call `tokio_tungstenite::connect_async`

Thank you

**Comment by agalakhov** [comment]
https://github.com/snapview/tokio-tungstenite/issues/336

**Comment by maxpowel** [comment]
Ah sorry, I tried to find any reference to this problem and I did not find it. Thank you

**Comment by malongshuai** [comment]
i changed my Cargo.toml and solved:
```toml
ring = { version = "0.17" }
rustls = { version = "0.23", features = ["ring","logging","tls12"], default-features = false }
tokio-tungstenite = { version = "0.23", features = ["rustls-tls-webpki-roots"] }
```
