### ISSUE TITLE
connect websocket failed

### ISSUE THREAD

**Issue by qq351469076** [snapview/tokio-tungstenite#365]
Hello, Author

When I requested exchange market data, I encountered an error. I suspect it might be a compatibility issue. The same Python code works fine when connecting, so I minimized the demo—it runs directly without problems. How should I resolve this?

```toml
[dependencies]
reqwest = { version = "0.12.20" }
sonic-rs = "0.5.1"
tokio-native-tls = "0.3.1"
tokio-tungstenite = { version = "0.27.0", features = ['native-tls'] }
tokio = { version = "1.45.1", features = ["rt", "rt-multi-thread", "macros"] }
```

```rust
use sonic_rs::JsonValueTrait;
use std::time::Duration;
use tokio_native_tls::native_tls;
use tokio_tungstenite::{Connector, connect_async_tls_with_config};

/// get kucoin exchange future public token
async fn get_kucoin_exchange_future_token() -> String {
    let client = reqwest::Client::new();

    let resp = client
        .post("https://api-futures.kucoin.com/api/v1/bullet-public")
        .send()
        .await
        .unwrap()
        .text()
        .await
        .unwrap();

    println!("Response Text:\n{}", resp);

    sonic_rs::get_from_str(resp.as_str(), &["data", "token"])
        .unwrap()
        .as_str()
        .unwrap()
        .to_string()
}

async fn start_ws(token: &str) {
    loop {
        // connect kucoin websocket
        let connector = native_tls::TlsConnector::builder().build().unwrap();

        let url = format!("wss://ws-api-futures.kucoin.com?token={token}&connectId=dstn2fg11");

        println!("{}\n{}", url, token);

        // connect kucoin
        let (ws_stream, _) =
            connect_async_tls_with_config(url, None, false, Some(Connector::NativeTls(connector)))
                .await
                .unwrap();

        println!("Kucoin connection successful");
    }
}

#[tokio::main]
async fn main() {
    let token = get_kucoin_exchange_future_token().await;
    println!("token:\n{}", token);

    start_ws(token.as_str()).await;

    loop {
        tokio::time::sleep(Duration::from_secs(60)).await;
    }
}

```

![Image](https://github.com/user-attachments/assets/38aeffbf-17b0-46c1-b4dd-9c8bbc471d15)
