### ISSUE TITLE
How to enable TLS?

### ISSUE THREAD

**Issue by wbrickner** [snapview/tokio-tungstenite#93]
Hello, I've gotten a modified example working, but I now need to use TLS.  I've been enjoying a protracted socratic argument with Cargo trying to enable TLS as a feature.

I'm no expert here, and it seems like it should be pretty simple.

Here's what I've got now:

```toml
[package]
name = "tokio-tungstenite-test"
version = "0.1.0"
authors = ["Will Brickner <wgbrickner@gmail.com>"]
edition = "2018"

[dependencies]
tokio-tungstenite = "*"
log = "0.4"
futures-util = { version = "0.3", default-features = false, features = ["async-await", "sink", "std"] }
tokio = { version = "0.2", default-features = false, features = ["io-std", "macros", "stream", "time"] }
tungstenite = { version = "0.10.0" }
futures-channel = "0.3"
```

When I run, attempting to connect over TLS, I get `thread 'main' panicked at 'Failed to connect: Url("TLS support not compiled in.")'`.

What can I do to enable TLS? Thanks!
